### ISSUE TITLE
Music Play Bug

### ISSUE THREAD

**Issue by 123eee-png** [esmBot/esmBot#314]
### Command that caused the error

/music play 

### Self-hosted instance?

No

### Error file

```

```
[error.txt](https://github.com/esmBot/esmBot/files/9548193/error.txt)

**Comment by ioletsgo** [comment]
It appears the bot was unable to connect to the voice channel. Are you sure it has the proper permissions to view and access the voice channel in question?

**Comment by Frontesque** [comment]
I also get this issue on my self hosted instance. I've done a bit of debugging and my initial reaction was that it was a LavaLink related issue. After some more debugging, **I realized it is not a lavalink related issue**. 

The only way that I have found to fix this bug is to restart the bot. **The lavalink server doesn't need to be restarted**.

This can get pretty annoying as I need to restart the bot multiple times per day sometimes. The bot has full permissions in the server and all of the special permissions _(Read Messages, Presence & Members)_

My stack trace is provided below:
```js
Message: Error: The voice connection is not established in 15 seconds
    at Connection.connect (/home/esm/esmBot/node_modules/.pnpm/shoukaku@​3.3.1/node_modules/shoukaku/dist/src/guild/Connection.js:98:23)
    at async Node.joinChannel (/home/esm/esmBot/node_modules/.pnpm/shoukaku@​3.3.1/node_modules/shoukaku/dist/src/node/Node.js:138:13)
    at async play (file:///home/esm/esmBot/utils/soundplayer.js:89:32)
    at async MusicAIOCommand.run (file:///home/esm/esmBot/commands/music/music.js?v=100:19:23)
    at async default (file:///home/esm/esmBot/events/interactionCreate.js:37:20)

Stack Trace: Error: The voice connection is not established in 15 seconds
    at Connection.connect (/home/esm/esmBot/node_modules/.pnpm/shoukaku@​3.3.1/node_modules/shoukaku/dist/src/guild/Connection.js:98:23)
    at async Node.joinChannel (/home/esm/esmBot/node_modules/.pnpm/shoukaku@​3.3.1/node_modules/shoukaku/dist/src/node/Node.js:138:13)
    at async play (file:///home/esm/esmBot/utils/soundplayer.js:89:32)
    at async MusicAIOCommand.run (file:///home/esm/esmBot/commands/music/music.js?v=100:19:23)
    at async default (file:///home/esm/esmBot/events/interactionCreate.js:37:20)
```

**Comment by mr-nv** [comment]
i also started getting this error now, but it only appears on 1 single server while the bot works perfectly fine on all other servers. the main thing that makes that exact server different is the fact that the bot usually gets kicked by the admins rather than by &disconnect

i dont know if that is the reason why this error appears, but this also rarely causes the bot to think that its in a voice channel when its not

**Comment by Frontesque** [comment]
This issue was fixed by #445 and #448

**Comment by TheEssem** [comment]
> This issue was fixed by #445 and #448

It still occurs occasionally on the main bot, which has YouTube support disabled.

**Comment by Frontesque** [comment]
> It still occurs occasionally on the main bot, which has YouTube support disabled.

interesting. this hasn't occured on my instance since the first pr. I'll look into it.
