### ISSUE TITLE
Bot leaves while people are listening

### ISSUE THREAD

**Issue by Niterux** [esmBot/esmBot#327]
### Describe the bug

Every time someone leaves the vc, the bot will stop playing and leave too, even if there are still people in the vc!

### Steps to reproduce

1. Play music with /music play command (in this case I was using an internet radio)
2. Have 1 or more other person join and leave the vc

### Expected behavior

Bot stays in vc to play for remaining people

### Screenshots

![Screenshot_2022-11-17-20-43-59-401](https://user-images.githubusercontent.com/110568869/202597588-f6d4abf0-a933-4f43-828c-ac31d143d369.jpeg)

### Self-hosted instance?

No

**Comment by TheEssem** [comment]
This ended up being an issue with Oceanic, should be fixed now.

**Comment by ljcool2006** [comment]
This is still an issue, this occurred to me today.

**Comment by ayesc9000** [comment]
I am still experiencing this issue, if anyone leaves the VC then the bot also leaves. The bot does not leave the VC if the last person leaves though.

**Comment by TheEssem** [comment]
Got confirmation that this is happening on the dev bot as well, reopening.

**Comment by ayesc9000** [comment]
The bot currently reports that the amount of people required to skip a track is zero. Could this be possibly related?

**Comment by TheEssem** [comment]
> The bot currently reports that the amount of people required to skip a track is zero. Could this be possibly related?

I believe so, yes; the skip command uses the same method for getting the current members in a voice channel as the leave handler.

**Comment by ayesc9000** [comment]
Wanted to weigh in and say that while I'm not sure when this happened (as I haven't updated my instance in a while), but the latest commit does not have this issue anymore.
